### ISSUE TITLE
Possible to run 2 instances at same time?

### ISSUE THREAD

**Issue by rrcdr** [nice-table/bitmex-scaled-orders#6]
Is it possible to run 2 instances of this for example if you have 2 or more bitmex accounts?

**Comment by nice-table** [comment]
Yes, you can achieve this by either (off the top of my head)

a) Use two different browsers (e.g. Firefox and Chrome). This is probably the best solution, since API keys will be remembered.

b) Use one browser, but open another instance in incognito mode. This has the inconvenience of API keys not being remembered for the incognito instance after you close it.

**Comment by rrcdr** [comment]
How do I get a second instance to run in a separate browser? Im on windows. I am opening 2 command prompts and running `npm run startup`. When I do this in the second command prompt I just get an error.

**Comment by nice-table** [comment]
You only need to run one instance of the server (npm run startup). It can handle multiple keys at the same time.

After you have started the server instance, open a second browser and go to the URL http://localhost:3006, type in your second API key and you should be good to go :)
